### ISSUE TITLE
TODO list for low level MRF models

### ISSUE THREAD

**Issue by Gnimuc** [DIR-Lab-SDU/MRF-Modeling-in-Image-Analysis#1]
- [ ] 2 Mathematical MRF Models
  - [x]  Ising Model
  - [x] Auto-Logistic Model
  - [ ] Auto-Binomial Model 
  - [ ] Auto-Normal Model
  - [x] Multi-level Logistic Model (MLL)
- [ ] 3.2 Image Restoration and Reconstruction
- [x] 3.4 Texture Synthesis and Analysis
  - [x] Sampling Algorithm 1 (Metropolis)
  - [x] Sampling Algorithm 2 (Gibbs)
- [ ] 7.1 Supervised Estimation with Labeled Data
  - [x] Pseudo-likelihood
  - [ ] Least Squares Fit
  - [x] Markov Chain Monte Carlo Methods(MCMC)
    - [x] Metropolis-Hastings Algorithm
    - [ ] Gibbs Sampler
- [ ] 7.2 Unsupervised Estimation with Unlabeled Data
  - [ ] Simultaneous Restoration and Estimation
  - [ ] Simultaneous Segmentation and Estimation
- [ ] 9.3 Minimization with Discrete Labels
  - [ ] Iterated Conditional Modes
  - [ ] Belief Propagation
- [ ] 10.1 Simulated Annealing
- [ ] 10.3 Graduated Nonconvexity
- [ ] 10.4 Graph Cuts
  - [x] Max-Flow
  - [x] Multilabel Graph Cuts
    - [x] α-expansion
    - [ ] α–β Swap
- [ ] 10.5.2 Hybrid GA: Comb Algorithm
- [ ] 10.6 Experimental Comparisons

**Comment by Gnimuc** [comment]
CC wudixiaopeng

**Comment by Gnimuc** [comment]
@wudixiaopeng

**Comment by Gnimuc** [comment]
@wudixiaopeng 根据12年TIP那篇文章作者给的代码, 可以把9.3 ICM重写一下加进来. #9

**Comment by Gnimuc** [comment]
@501306162 建议挑几个label为[`up for grabs`](https://github.com/DIR-Lab-SDU/MRF-Modeling-in-Image-Analysis/labels/up%20for%20grabs)的issue实现一下，并review现有代码。

**Comment by Gnimuc** [comment]
不熟悉GitHub flow可以看看这个培训视频http://www.bilibili.com/video/av7893882/
